
// This file has been generated by the GUI designer. Do not modify.
namespace DCReleaseTools.Dialogs
{
	public partial class GenerateControlDialog
	{
		private global::Gtk.Entry txtResourceName;

		private global::Gtk.Button btnCancel;

		private global::Gtk.Button btnOK;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget DCReleaseTools.Dialogs.GenerateControlDialog
			this.Name = "DCReleaseTools.Dialogs.GenerateControlDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child DCReleaseTools.Dialogs.GenerateControlDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "generateDialog";
			w1.BorderWidth = ((uint)(2));
			// Container child generateDialog.Gtk.Box+BoxChild
			this.txtResourceName = new global::Gtk.Entry();
			this.txtResourceName.CanFocus = true;
			this.txtResourceName.Name = "txtResourceName";
			this.txtResourceName.IsEditable = true;
			this.txtResourceName.InvisibleChar = '●';
			w1.Add(this.txtResourceName);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(w1[this.txtResourceName]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Internal child DCReleaseTools.Dialogs.GenerateControlDialog.ActionArea
			global::Gtk.HButtonBox w3 = this.ActionArea;
			w3.Name = "dialog1_ActionArea";
			w3.Spacing = 10;
			w3.BorderWidth = ((uint)(5));
			w3.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.btnCancel = new global::Gtk.Button();
			this.btnCancel.CanDefault = true;
			this.btnCancel.CanFocus = true;
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.UseStock = true;
			this.btnCancel.UseUnderline = true;
			this.btnCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.btnCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w3[this.btnCancel]));
			w4.Expand = false;
			w4.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.btnOK = new global::Gtk.Button();
			this.btnOK.CanDefault = true;
			this.btnOK.CanFocus = true;
			this.btnOK.Name = "btnOK";
			this.btnOK.UseStock = true;
			this.btnOK.UseUnderline = true;
			this.btnOK.Label = "gtk-ok";
			this.AddActionWidget(this.btnOK, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w3[this.btnOK]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 436;
			this.DefaultHeight = 122;
			this.Show();
		}
	}
}
